---
# Test playbook
# TODO: remove this file before merging to master
- hosts: all
  gather_facts: False
  tasks:
  - name: Populate service facts
    ansible.builtin.service_facts:

  - name: Print service facts
    ansible.builtin.debug:
      msg: systemd-resolved.service detected!
    when: "'systemd-resolved.service' in ansible_facts.services"
 
