---
# Ansible playbook with tests
- name: Verify
  hosts: all
  become: True
  gather_facts: False
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: bind-utils
      state: present
  - name: Query CoreDNS server
    ansible.builtin.command: dig +noall +short @127.0.0.1 molecule.home
    args:
      warn: False
    changed_when: False
    ignore_errors: yes
    register: dig_out
  - name: CoreDNS server availability check
    debug:
      msg: CoreDNS server is available
    when: dig_out.rc == 0
  - name: Zone check
    debug:
      msg: "IP address for 'molecule.home' is {{ dig_out.stdout }}. Zone 'home.' is configured properly"
    when: dig_out.stdout == "192.168.200.50"
